### ISSUE TITLE
Add more typed parameters to commands

### ISSUE THREAD

**Issue by williamhatcher** [ire4ever1190/dimscmd#3]
From https://github.com/ire4ever1190/dimscmd/blob/6399e5313146c6373d6dcd146b543ea47efac263/src/dimscmd.nim#L171 it looks like only `int` and `string` are the supported types. Lets see if we can't add User/Member, Role, Channel, and Guild types.

it would parse full names (eg: William_CTO#5415), pings/mentions @William_CTO (which is really `<@!ID>`), etc 
This could then return the id of the user/role/channel, etc or a User object, etc fetched from the Discord API

**Comment by ire4ever1190** [comment]
Certainly something that would be very useful. If you want to have a crack at it then I recommend looking [here](https://github.com/ire4ever1190/dimscmd/blob/master/src/dimscmd.nim#L185) since this is where the code is injected that parses the options passed in. You can see that I started work on trying to parse more complex options but I have been distracted with slash commands 😆

**Comment by krisppurg** [comment]
Array of (string, int, bool) or booleans as well, for example: slash commands.

**Comment by ire4ever1190** [comment]
I added sequences and Channels in latest commit
working on User and Roles (along with sequence version for them)

**Comment by ire4ever1190** [comment]
Finally all done, if any more types are needed it is simple enough to add with the new scanning api
